# Generated by Django 4.2.4 on 2023-08-26 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('tipoCancha', models.CharField(choices=[('Padel', 'Padel'), ('Futbol', 'Futbol'), ('Polideportivo', 'Polideportivo')], max_length=60)),
                ('fechaInicio', models.DateTimeField(verbose_name='Fecha y hora inicio')),
                ('fechaFin', models.DateTimeField(verbose_name='Fecha y hora fin')),
                ('celular', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Celular')),
                ('afiliado', models.IntegerField(blank=True, default='0', null=True)),
                ('asistio', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=9)),
                ('montoRecaudado', models.IntegerField(blank=True, default='', null=True)),
                ('observaciones', models.TextField(blank=True, default='No se registraron datos', null=True)),
                ('turnoDadoPor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TurnoDadoPor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
