# Generated by Django 3.2.4 on 2021-06-27 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
    ]
