# Generated by Django 3.2.4 on 2021-06-27 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
    ]
