# Generated by Django 3.2.4 on 2021-06-27 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turno_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='celular',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Número debe ser ingresado en formato '+54XXXXXXXXXX'.", regex='^\\+?54?\\d{10}$')], verbose_name='Celular'),
        ),
    ]
