# Generated by Django 3.2.4 on 2021-07-04 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0004_alter_turno_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='asistio',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='Si', max_length=9),
        ),
        migrations.AddField(
            model_name='turno',
            name='montoRecaudado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='turno',
            name='turnoDadoPor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TurnoDadoPor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turno',
            name='celular',
            field=models.CharField(max_length=11, unique=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha y hora'),
        ),
    ]
