# Generated by Django 3.2.4 on 2021-07-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_auto_20210703_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='celular',
            field=models.CharField(max_length=11, verbose_name='Celular'),
        ),
    ]
