# Generated by Django 3.2.4 on 2021-07-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_alter_turno_celular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='turno',
            name='celular',
            field=models.CharField(max_length=11, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='montoRecaudado',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
