# Generated by Django 3.2.4 on 2021-07-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_auto_20210707_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='montoRecaudado',
            field=models.IntegerField(default='', null=True),
        ),
    ]
