# Generated by Django 4.2.4 on 2023-08-21 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_alter_turno_montorecaudado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='afiliado',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
